fix: ending a stage sets pause timeout
ZPTXDev/Quaver pull request #235
Opened 2022-04-21 04:23 UTC by Xayanide

Fixes #155

### Thank you for your interest in contributing!
Before proceeding, please review the [guidelines for contributing](https://github.com/ZapSquared/Quaver/blob/master/CONTRIBUTING.md).

- [x] Are you targeting the `next` branch? (right side)
- [x] Did you review the guidelines for contributing?
- [x] Does your code pass linting checks?
- [ ] Did you document your code?
- [ ] Is this change necessary?

### Scope of change
- [ ] Major change
- [x] Minor change
- [ ] Documentation only

### Type of change
- [x] Bug fix
- [ ] Feature
- [ ] Other

### Description
Please describe the changes.

I have no idea why. Not touching this code anymore. Please analyze it why, provide better approach or alternatives if so.

Take a look at the video for testing demo.

https://user-images.githubusercontent.com/18362871/164371526-11b43338-a1da-480e-8209-9036ccf8d3a4.mp4

2022-05-03 02:43 UTC, zapteryx requested changes

2022-05-03 02:43 UTC, zapteryx commented on events/voiceStateUpdate.js
> +		}
i'm still positive there's a way to do this without abusing await, just not sure how yet

2022-05-03 02:43 UTC, zapteryx commented
put this on hold for now, will check back on it in a bit

2022-07-13 07:53 UTC, Xayanide commented
This pull request will be recreated.

2022-07-13 07:53 UTC, closed without merging